### ISSUE TITLE
@INC is not OK at start up when installed in D:\...

### ISSUE THREAD

**Issue by bojinlund** [StrawberryPerl/Perl-Dist-Strawberry#130]
First of all, thank you all for picking up the project and making new releases - these were missed badly! 

I have downloaded https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_5380_5361/strawberry-perl-5.36.1.1-64bit.msi and installed it in **D:\ins\strawberry**.

Running this using Windows 10:
``````
print "hello";
#use lib "d:/ins/strawberry/perl/vendor/lib/";
use Path::Tiny;
``````
I get (without use lib):
``````
Can't locate Path/Tiny.pm in @INC (you may need to install the Path::Tiny module)
(@INC contains: /usr/lib/perl5/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/vendor_perl
 /usr/share/perl5/vendor_perl /usr/lib/perl5/core_perl /usr/share/perl5/core_perl)
at test_1.pl line 3.
BEGIN failed--compilation aborted at test_1.pl line 3.
``````
With “use lib” there is no message.

Med vänliga hälsningar
Bo Johansson

**Comment by xenu** [comment]
You're running the wrong perl binary, most likely your `PATH` contains cygwin or MSYS.

You can verify that with `where perl`, or if you're using PowerShell: `(gcm perl).path`.

**Comment by shawnlaffan** [comment]
Are you sure this is running with Strawberry Perl's perl.exe?  

The paths in ```@INC```  are not windows paths and make me suspect that a cygwin or msys perl is being picked up instead.  An example where this can happen is when Git for Windows is installed and its ```...\usr\bin``` dir has been added to the path.


What happens when you run these commands?

```cmd
:: list all perls in path
where perl

:: list the location of the perl that is run 
:: (should be the first result in the previous command)
perl -E"say $^X"
```

**Comment by bojinlund** [comment]
Thank you! Spot on.

I had “C:\Program Files\Git\usr\bin” before the path to Strawberry perl.
By installing a newer version of Git, “C:\Program Files\Git\usr\bin” was moved later in path.

Is it possible to get a warning by the installation of Strawberry perl, that there is another perl earlier in path?

**Comment by csjewell** [comment]
Somebody would have to write some more C code to check for that within the MSI builds - and it'd be impossible for portableshell builds.

**Comment by sisyphus** [comment]
If one just wants to ensure that the perl that's being run is a specific Strawberry Perl, then one can start by setting the PERL5OPT environment variable  to<code>-MStrawcheck</code>.
With that environment variable set, whenever perl is run it will first try to load the Strawcheck.pm file and croak if that file is not loadable.
All you then need to do is create a Strawcheck.pm file that contains just <code>1;</code> followed by a newline, and place that file into the <code>\@INC</code> of each of the perl(s) that you are prepared to let run.

For example, with my Strawberry-5.38.0, a few lines down from the beginning of portableshell.bat, there's a line <code>set PERL5OPT=</code>.
I change that line to <code>set PERL5OPT=-MStrawcheck</code> and place the aforementioned Strawcheck.pm into the perl/site/lib folder.
When I execute portableshell.bat, a new cmd.exe shell opens up in the usual way, and perl is fully functional.
```
----------------------------------------------
 Welcome to Strawberry Perl Portable Edition!
 * URL - http://www.strawberryperl.com/
 * see README.TXT for more info
----------------------------------------------
Perl executable: C:\sp\_64\sp-5.38.0\perl\bin\perl.exe
Perl version   : 5.38.0 / MSWin32-x64-multi-thread

C:\sp\_64\sp-5.38.0>perl -e "print 'All OK';"
All OK
C:\sp\_64\sp-5.38.0>
```

But then no other perl will run in that shell because no other perl can locate Strawcheck.pm.
```
C:\sp\_64\sp-5.38.0>C:/perl-5.38.0-1310-mcf/bin/MSWin32-x64-multi-thread/perl -V
Can't locate Strawcheck.pm in @INC (you may need to install the Strawcheck module) (@INC entries checked: C:/perl-5.38.0-1310-mcf/site/lib/MSWin32-x64-multi-thread C:/perl-5.38.0-1310-mcf/site/lib C:/perl-5.38.0-1310-mcf/lib/MSWin32-x64-multi-thread C:/perl-5.38.0-1310-mcf/lib).
BEGIN failed--compilation aborted.
```
Even if this Strawberry Perl tries to run another perl (as a system command), it still won't work:
```
C:\sp\_64\sp-5.38.0>perl -le "`C:/perl-5.38.0-1310-mcf/bin/MSWin32-x64-multi-thread/perl -V`;"
Can't locate Strawcheck.pm in @INC (you may need to install the Strawcheck module) (@INC entries checked: C:/perl-5.38.0-1310-mcf/site/lib/MSWin32-x64-multi-thread C:/perl-5.38.0-1310-mcf/site/lib C:/perl-5.38.0-1310-mcf/lib/MSWin32-x64-multi-thread C:/perl-5.38.0-1310-mcf/lib).
BEGIN failed--compilation aborted.
```
Whenever I see that failure, I will know that  a perl that is not this Strawberry Perl has been invoked.

But it does rely on PERL5OPT being set appropriately, and the whole thing can be turned of simply by clearing PERL5OPT.

If one wants to allow other perl's to be invoked but wants such an event to be announced, then these  "other perls" would be given a Strawcheck.pm that emits a warning  - eg "Oracle perl has been loaded !!!", or "MSYS2 perl has been loaded!!!", ...

A similar approach should also work with Strawberry Perls installed by the msi package.

Cheers,
Rob
