### ISSUE TITLE
Support for upgrade

### ISSUE THREAD

**Issue by Thilas** [StrawberryPerl/Perl-Dist-Strawberry#19]
As per https://github.com/Thilas/chocolatey-packages/issues/13, it looks like the MSI setup of StrawberryPerl does not support upgrades of an existing install. Why is that? Could it be supported?

If not, what is the best course of action for the chocolatey package I'm maintaining? For instance, if I uninstall an existing install before installing the new version, is there any chance a user will loose something (i.e. packages, config, ...)? Any recommendation?

**Comment by kmx** [comment]
MSi upgrade is partly supported:
* but only: 5.32.m.n >> 5.32.x.y
* not: 5.32.m.n >> 5.33.x.y

It is how perl binary compatibility works not only on MS Windows.

**Comment by alexchandel** [comment]
Can we reopen this to support upgrading cases from e.g. `5.38` to `5.40`?  This currently does not seem to work.

**Comment by shawnlaffan** [comment]
An in-place upgrade from 5.xx to 5.yy needs a complete uninstallation first.  

FWIW, we are using Wix v3 so perhaps there are options under that.  However, Wix is at now at v5 so it would be good to upgrade to that, or replace it with another MSI build system.  

Config files are under https://github.com/StrawberryPerl/Perl-Dist-Strawberry/tree/master/share/msi

I'll leave this closed for now but PRs are always welcome.

**Comment by alexchandel** [comment]
I think there is a way for Wix to perform a complete uninstall of the previous version during the installation ([here](https://stackoverflow.com/questions/26336332/force-uninstalling-before-installing-any-version-with-wix-installer)), but I think the trick is limiting it to the second version number, since it sounds like you do an in-place upgrade for third digit upgrades.
