### ISSUE TITLE
Please update nuget.org with a StrawberryPerl that has a new sqlite and includes the license

### ISSUE THREAD

**Issue by shueybubbles** [StrawberryPerl/Perl-Dist-Strawberry#23]
Hello,
We are getting flagged for using open source components containing a distribution of sqlite that has several documented vulnerabilities, such as https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-19646 and https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-8457

Can you publish a new package using an updated sqlite? Alternately, is there a way to get a package without it?

Also, the licenseUrl in the nuspec points to a basic web site, not to the actual license. Can you fix the nuspec to include the actual license?
thx

**Comment by csjewell** [comment]
Other people have created the packages and package information on nuget.org. So you would have to contact the people who have created those packages.

I would be surprised if the current version on strawberryperl.com does not include fixes for those CVE's, plus, since Strawberry Perl includes the means to compile modules, an updated version of DBD::SQLite can be installed easily, given internet access or access to a download of the current DBD-SQLite .tar.gz.

As for a license, there is not ONE license, since Strawberry Perl is a compilation of packages, much like a Linux distribution.  https://github.com/StrawberryPerl/Perl-Dist-Strawberry/raw/master/share/extra-files/licenses/License.rtf (displayed within the .msi upon installation) describes that situation, and shows an attempt to compile the major licenses used. Maybe a webpage on strawberryperl.com containing that text could be created. Code written by the Strawberry Perl project itself (to build the .msi, and supporting code for it) usually has a 'same as Perl' license, however.

**Comment by adamkennedy** [comment]
It appears that others are redistributing Strawberry Perl, bug reports should be directed to those individuals.

You can see the identities of the 4 redestributors here...

https://www.nuget.org/packages?q=Strawberry+Perl
