### ISSUE TITLE
[BUG] Windows Installer issues

### ISSUE THREAD

**Issue by levicki** [StrawberryPerl/Perl-Dist-Strawberry#32]
I am submitting this as a single issue because all those problems are related.

1. Installer does not allow installing to `C:\Program Files` or any other path with spaces in it. It's 2021, paths with spaces are the norm. Python, and pretty much anything else such as Git, and CMake to name just a few, can handle it, why not Perl?
2. Installer does not follow standard logic of installing into a directory named after a program it is installing (i.e. `C:\Perl`). The word "Strawberry", even though it is part of the whole distribution name, by itself does not have a strong association with Perl language and at least to me implies that a company named "Strawberry" is making a directory where other applications released by them will also be installed.
3. Because of 2, choosing the install directory is confusing, and you can easily make a mistake thinking that `Perl` subdirectory will be created in selected directory. For example if you select `C:\Tools` you would expect it to create a subdirectory `Perl` in it. Instead it just spills its guts in `C:\Tools` which brings us to the biggest problem.
4. When uninstalling, the installer **deletes all other files it finds in the root of `C:\Tools`** even though it wasn't the one who put them there. Even free installer tools such as InnoSetup know to only remove files they added to the system.
5. Even on the fastest of systems (i7-9800X, Samsung 970 Pro M.2 SSD, 64 GB RAM) installation and uninstallation is attrociously slow with the current installer. I have seen no other MSI packages behaving in this way.

My proposal to fix this is as follows:

* Install to `C:\Program Files\Perl` by default under x64 OS, (`C:\Program Files (x86)\Perl` under x86 OS).
* Either fix existing installer to not remove files it doesn't own and to work faster, or switch to using another faster installer which is capable of not deleting user files.

**Comment by levicki** [comment]
@genio 

Judging by [your condescending response](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/issues/11#issuecomment-992498534) which amounted to "you're wrong because I say so" without explaining why VS licensing is an issue for Perl and whether that has been discussed with Microsoft, I am now sure that this issue will be dismissed in a similar manner so I will just go ahead and save you the trouble by closing it myself.

The crux of what I was trying to say there and what I was saying here before you blew me off is that open-source projects could get more exposure (and likely more contributors as a result) if they integrated native build systems for other platforms they decided to distribute themselves on, and if they followed certain conventions of those platforms when it comes to installation and configuration.

But it seems you prefer to fade into obsolescence by antagonizing users so I will leave you to it. Have a nice day.

**Comment by genio** [comment]
@levicki Right. We worked a lot to get MS to change their licensing and they did quite some time back: https://developercommunity.visualstudio.com/t/CC-compiler-and-linker-free-CLI-only/10042178#T-N10280992

Since that point, we've needed Perl itself to be UCRT compatible. With version 5.40, that's now in place. This is something we're looking into: https://github.com/StrawberryPerl/spbuild/tree/main/msvc

**Comment by levicki** [comment]
That's good news then. Hopefully paths with spaces will be next :-)

**Comment by genio** [comment]
@levicki If you have some expertise in the area, we'd appreciate assistance. Take a look into https://github.com/StrawberryPerl/spbuild/ and https://github.com/StrawberryPerl/spbuild/tree/main/msvc to see _how_ we're going about the build so far.

**Comment by mohawk2** [comment]
Perl "in space" (installed in a directory with a space in its name - more accurate but less catchy) is something that had show-stopping problems installing many CPAN libraries for a long time, due to ExtUtils::MakeMaker using make which had problems with paths for Perl system stuff having spaces in being split on spaces.

This remains a problem, and my workaround of asking the system to use "short" filenames (8.3) in such circumstances is now becoming less available due to such filenames being increasingly turned off on default Windows installations and/or individual filesystems on those installations. See https://github.com/perl/perl5/issues/16804 for a bit more, and https://stackoverflow.com/questions/9838384/can-gnu-make-handle-filenames-with-spaces for StackOverflow discussion on GNU Make's issues with this. The SO answer links to the GNU Make bug that tracks this (https://stackoverflow.com/questions/9838384/can-gnu-make-handle-filenames-with-spaces), and only deal with using things in the shell, not as dependencies. Backwards compatibility makes this a problem for GNU Make.

Ironically enough, my making GNU Make usable in EUMM on Windows prompted the then-maintainer of Strawberry Perl, kmx, to switch it to use GNU Make instead of dmake. This then made my intent to make dmake handle this properly somewhat redundant, so I have yet to do so.

Fundamentally, the root of this problem is Strawberry Perl's choice of "make" utility, together with that utility's interaction with EUMM as well as its ability to smoothly handle "Perl in space".

**Comment by mohawk2** [comment]
@levicki When you say "hopefully", are you waiting for someone else to take action on this, or are you offering to do something about it? :-)

**Comment by levicki** [comment]
> @levicki If you have some expertise in the area, we'd appreciate assistance. Take a look into https://github.com/StrawberryPerl/spbuild/ and https://github.com/StrawberryPerl/spbuild/tree/main/msvc to see _how_ we're going about the build so far.

I will definitely take a look and try building it to see if I hit any obstacles. However, I am mostly Perl end-user (on Windows at that) who occasionally has to run a perl script without dependencies so my knowledge of CPAN and build process for that is non-existent.

@mohawk2

/rant ON

I have seen the bug report for GNU make and I want to vomit. It's one of those "hard" issues which nobody ever wants to fix so it has remain open for what, 22 years and counting?

If I were a maintainer of anything (perhaps a good thing I am not) I would have ripped GNU make out of any and all of my projects and replaced it with something else letting them procrastinate on implementing proper path/name support for another century if they wish so as they become less and less relevant.

Seriously, make, dmake, whatever.

Just use CMake in 2024 &mdash; it works well.

It's platform independent, it provides native Windows toolchain support and hey it even supports spaces in paths.

If people want to continue using GNU make, put that stuff in contrib and stop supporting it.

/rant OFF

Phew, I really get too triggered by this stuff, sorry about that.

> When you say "hopefully", are you waiting for someone else to take action on this, or are you offering to do something about it? :-)

Yes, I won't lie, I was hoping maintainers would be interested in improving this aspect of Strawberry Perl.

Of course I am open to collaboration, but I do have a full time job and I have no knowledge of current Perl build environment so I am not sure how quickly (if at all?) I could be of any help to you.

What I would suggest is to seriously consider CMake as a possible replacement for the archaic GNU make. I'd like to hear your thoughts on whether that would be feasible.

**Comment by genio** [comment]
`cmake` isn't really an alternative to `gmake`, `dmake`, or `nmake`. 

CMake is used to generate a project. CMake parses a given `CMakeLists.txt` file and can then generate Makefiles that can then be parsed by `nmake`/`dmake`/`gmake`.

In the Perl world, we already generate Makefiles for modules with `ExtUtils::MakeMaker`. Though, some Perl modules build with pure Perl from `Module::Build` or something similar.

Using an alternative to `gmake` (which is currently the best one) wouldn't really help us.

Microsoft's `nmake` works only if we're using a MSVC-built Perl.
`dmake` has been pretty much replaced everywhere by `gmake`.

**Comment by genio** [comment]
Ninja is an entirely other build system. It's not capable of building from Makefiles. CMake can be used to generate builds for Ninja, but that won't help us.

Perl itself is built with `Makefile`s. Perl modules are either built with pure-Perl or from `Makefile`s. We _have_ to use and build using `Makefile`s and thus our only real option is `gmake`.

**Comment by genio** [comment]
I'm going to lock this particular issue at this point. If we want to continue discussions, we can take it to the [Discussions](https://github.com/StrawberryPerl/Perl-Dist-Strawberry/discussions) area.
