### ISSUE TITLE
Bug in library?

### ISSUE THREAD

**Issue by PhilterPaper** [StrawberryPerl/Perl-Dist-Strawberry#34]
I'm not sure if this is the right place to report this, but here goes... I have some compiler warnings when installing Text::KnuthPlass, which compiles some XS code (C++). The full description is in PhilterPaper/Text-KnuthPlass#8. It's hard to tell where in my code it's going off the rails (possibly line 2 include of perl.h). In KnuthPlass.xs line 153 (function _init_nodelist, last line of CODE section) I tried changing
```
    hv_stores((HV*)self, "activeNodes", ((IV)activelist));
```
to
```
    hv_stores((SV*)self, "activeNodes", ((IV)activelist));
```
but no change to the warning message about mismatched prototypes. Needless to say, I'm not happy about making semi-random changes like this, without understanding what's going on. Anyway, I wanted to bounce this off of somebody else to see if the problem is in my code or somewhere in the C/C++ libraries supplied with Strawberry Perl. I'd appreciate it if someone with experience in this area could try an install of Text::KnuthPlass and see if they get the same error, and if they can tell where it is (and whether _I_ need to fix my code, or someone needs to fix the library).

This happens in both Perl 5.26.1 and 5.32.1, built for Windows 10 64bit (MSWin32-x64-multi-thread). Please don't yell at me if this is bad XS code -- I inherited it from someone else who wrote it long ago :-).  Thanks!

**Comment by sisyphus** [comment]
The first argument that Perl_hv_common_key_len() receives is the context arg (_aTHX), and the 6th (ie second last argument) is supposed to be a pointer to SV ..... but it's instead an integer (IV).
This is of no consequence so long as the integer, when used as a pointer, points to the intended SV .... and that's the case here.
Of course, the compiler doesn't know that this condition will always be met ... so the warning is emitted.
We encounter this warning from time to time with perl but if the tests pass and nothing  crashes, I just ignore it. (Not everyone is so lenient.)

I expect (untested) that the very same warning appears on other systems that enable [-Wint-conversion] warnings.
If you want to silence the warning you could (as hinted to in the warning message) explicity cast that IV to SV* when it's passed to hv_common_key_len(). I don't know how easy that would be. 

Here's a little Inline::C demo that illustrates the issue, though with pointer-to-int rather than pointer- to-SV.
```
use strict;
use warnings;

use Inline C => Config =>
  BUILD_NOISY => 1,
;

use Inline C =><<'EOC';

void _deref(int * x) {
   printf("%d\n", *x);
}

void foo(int in) {
  IV addr;
  int *x;
  x = &in;

  printf("PTR:  %lld\n", x);
  addr = (IV)x;
  printf("ADDR: %lld\n", addr);
/*  _deref(x);        *//* works fine, no warning */
/*  _deref(addr);     *//* works fine, but warns  */
  _deref((int*)addr);   /* works fine, no warning */
}

EOC

foo(-1017);
```
All is fine so long as the two printf() statements emit the same numeric value, as they should.
However, if and only if you choose the "_deref(addr)" form, you will then see the warning emitted during the compilation phase of the script.

**Comment by PhilterPaper** [comment]
Thank you very much for your quick response! I changed the line in question to 
```
    hv_stores((HV*)self, "activeNodes", ((SV *)activelist));
```
and it compiles without warning and the tests and examples still work properly. 

It sure would be nice if the compile process could report back a clearer indication of where it found the problem, but now that I've seen the fix for this one, I think I can understand what the original error messages are saying. I'll go ahead and close this ticket, as that seems to have resolved the problem (not a major problem, admittedly, but I'm something of a stickler for clean compiles). Again, thanks!
