### ISSUE TITLE
Strawberry Perl not working with System Path when running system()

### ISSUE THREAD

**Issue by HumanGamer** [StrawberryPerl/Perl-Dist-Strawberry#41]
When I run any command in backticks or system() and the exe file is not in the same directory as the script it will fail with error code 65280 and generates 2 empty 0 byte files in the same folder. (the program name entered in the system command and cmd.exe)

for example the following script will fail to run the command and will generate nasm and cmd.exe in the folder
```perl
#!/usr/bin/perl

my $nasmval = `nasm -v`;
print("Output is: $nasmval\n");
```

and using the system command instead outputs 65280.

I've been trying to compile a library through vcpkg that depends on OpenSSL and that uses Strawberry Perl. Until this can be solved I am unable to use any vcpkg library that requires OpenSSL.

**Comment by sisyphus** [comment]
I  can't reproduce that behaviour with 64-bit Strawberry Perl 5.32.1.
If nasm is in the path, I get:
```
Output is: NASM version 2.15.05 compiled on Apr 21 2022
```
Otherwise I get:
```
'nasm' is not recognized as an internal or external command,
operable program or batch file.
Output is:
```
In neither case is nasm in the cwd ... nor is it in the same directory as the script.

Which version of Windows do you have ? (I'm on Windows 7.)
What does <code>perl -v</code> output for you ?
Does /usr/bin/perl.exe exist ?
Does the output change if you replace <code>#!/usr/bin/perl</code> with, say, <code>#!perl</code> ?
Are there any hints if you <code>use warnings;</code> and <code>use strict;</code> in that script ?
Do you execute the script as <code>perl script.pl</code> ? (If not, what happens when you do run it that way ?)
Or do you execute the script as <code>script.pl</code> ?

Cheers,
Rob

**Comment by HumanGamer** [comment]
**Which version of Windows do you have ? (I'm on Windows 7.)**
I'm on Windows 10 x64 21H2 (Build 19044.1766)

**What does ``perl -v`` output for you ?**
``perl -v`` gives the following 
![image](https://user-images.githubusercontent.com/39096122/174480835-da64d4a0-d15e-4a87-a80b-78985e88d788.png)

**Does /usr/bin/perl.exe exist ?**
I don't know where /usr/bin/perl.exe would be on a windows system. I just looked up the basics of perl so I could figure out why OpenSSL wouldn't compile, and it said to do that.

**Does the output change if you replace ``#!/usr/bin/perl`` with, say, ``#!perl`` ?**
changing it to ``#!perl`` doesn't change anything

**Are there any hints if you ``use warnings;`` and ``use strict;`` in that script ?**
Yes, with the following script:
```perl
#!usr/bin/perl

use warnings;
use strict;

my $nasmval = system("nasm -v");
print("Output is: $nasmval\n");
```
The output is:
```
Can't spawn "cmd.exe": No such file or directory at test.pl line 6.
Output is: 65280
```

**Do you execute the script as ``perl script.pl`` ? (If not, what happens when you do run it that way ?)**
Yes

**Or do you execute the script as ``script.pl`` ?**
That just opens it in Notepad++.

Also, one thing I forgot to mention before is that, I tried ActivePerl and Msys Perl and they worked correctly, only Strawberry Perl has this issue.

**Comment by HumanGamer** [comment]
I just solved the issue!

I temporarily disabled Malwarebytes Anti-Malware (Premium) and now it works correctly.

The only issue is that obviously I want to leave it enabled but I'm not sure what file to add to the exceptions when running vcpkg as it downloads perl automatically.

Either way, that was the issue.

Is there any way you could update Strawberry Perl to not be affected by Malwarebytes? ActivePerl and Msys Perl had no issues.

**Comment by sisyphus** [comment]
Odd that it doesn't affect ActivePerl, as I'm not aware of any difference between AP and SP that would account for that. (I'm assuming the AP installation is *not* an old one.)

I always think that, as regards antivirus software, it's up to the user/provider of that software to accommodate perl, rather than the other way around.
But if you can identify something that StrawberryPerl can do to help, then it's certainly worth pointing it out.

Cheers,
Rob

**Comment by HumanGamer** [comment]
I would be interested in debugging this, though i'm not that familiar with perl. Would you mind telling me if there's anyway I could get the source code of Strawberry Perl and compile/debug it in Visual Studio?

**Comment by genio** [comment]
@HumanGamer I'm not sure what ActivePerl uses for a compiler these days, but Strawberry is built with MSYS2+MinGW. The source for Perl itself is in the Perl repo: https://github.com/perl/perl5

There are instructions there for compilation: https://github.com/Perl/perl5/blob/blead/README.win32

If you find anything helpful, we'd appreciate it.

**Comment by sisyphus** [comment]
@HumanGamer Strawberry just uses the official perl source.
They do some customized stuff but AFAIK, nothing that would be relevant to your issue.
In fact, I'm more suspicious of the influence that your MSYS2 installation might be having, rather than Strawberry Perl itself - but I don't really have much of an understanding of the things that AV software might do.

In addition to the link to bleadperl that @genio has provided, 5.32.1 source can be downloaded from:
https://cpan.metacpan.org/authors/id/S/SH/SHAY/perl-5.32.1.tar.gz

And latest stable perl release is at:
https://cpan.metacpan.org/authors/id/R/RJ/RJBS/perl-5.36.0.tar.gz

When I build perl with Visual Studio 2019, I just cd to the win32 directory in the perl source and run:

nmake CCTYPE=MSVC142 INST_TOP=C;/wherever/perl test
nmake CCTYPE=MSVC142 INST_TOP=C;/wherever/perl install

For a debug build you'd add <code>CFG=Debug</code>.

Just go through the win32/Makefile - it's pretty well self documented, and lists CCTYPE settings for all of the supported MS compilers, along with various other configuration options that I think you can ignore.

If your VS compiler is 32-bit, then you'll also need to specify <code>WIN64=undef</code>

Cheers,
Rob

**Comment by HumanGamer** [comment]
Alright thank you, I have some other matters to take care of for now, but I will try this out later and see if I can find the cause.

**Comment by HumanGamer** [comment]
Malwarebytes just received an update that fixed the issue.

Unfortunately I can no longer debug the difference between perl versions as both are now working.

Thanks for the help though.
